### ISSUE TITLE
Error logging issue for graph catalog

### ISSUE THREAD

**Issue by alenegro81** [neo4j/graph-data-science#103]
When logging a "NoSuchElementException" in the graph catalog, it should be logged also the database. The example below is a bit confusing. In my case I should have noticed that I was using the wrong db :-) but if the error contains the suggestion of the database would be easier to identify the issue.  

Caused by: java.util.NoSuchElementException: Graph with name `drkg-undirected` does not exist. Did you mean `drkg-undirected`?
	at org.neo4j.graphalgo.core.loading.GraphStoreCatalog$UserCatalog.get(GraphStoreCatalog.java:207)
	at org.neo4j.graphalgo.core.loading.GraphStoreCatalog$UserCatalog.get(GraphStoreCatalog.java:192)
	at org.neo4j.graphalgo.core.loading.GraphStoreCatalog.get(GraphStoreCatalog.java:45)
	at org.neo4j.graphalgo.AlgoBaseProc.memoryEstimation(AlgoBaseProc.java:256)
	at org.neo4j.graphalgo.BaseProc.tryValidateMemoryUsage(BaseProc.java:187)
	at org.neo4j.graphalgo.BaseProc.tryValidateMemoryUsage(BaseProc.java:172)
	at org.neo4j.graphalgo.AlgoBaseProc.validateMemoryUsageIfImplemented(AlgoBaseProc.java:330)
	at org.neo4j.graphalgo.AlgoBaseProc.compute(AlgoBaseProc.java:170)
	at org.neo4j.graphalgo.AlgoBaseProc.compute(AlgoBaseProc.java:155)
	at org.neo4j.gds.embeddings.graphsage.GraphSageWriteProc.write(GraphSageWriteProc.java:53)

**Comment by AliciaFrame** [comment]
Thanks for opening this - we're going to improve our error messaging around multi-database & named graphs. We'll let you know when it's merged 🙂

**Comment by s1ck** [comment]
Thanks for the hint. We changed the error message to output the current db, e.g. `Graph with name `foo` does not exist on database `my_db`. Did you mean ... `.
