### ISSUE TITLE
It takes forever in executing the randomWalk algorithm

### ISSUE THREAD

**Issue by AlexOugh** [neo4j/graph-data-science#131]
I upgraded the library to 1.6.5 and tried, but 'listProgress' returns nothing as attached.

And I see this message in the log file.

2021-09-23 01:19:27.537+0000 INFO RandomWalkProc: overall memory usage 0 Bytes
Exception in thread "Thread-20" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 108
at org.neo4j.graphalgo.core.utils.paged.HugeIntArray$SingleHugeIntArray.get(HugeIntArray.java:280)
at org.neo4j.graphalgo.core.huge.TransientAdjacencyList.degree(TransientAdjacencyList.java:154)
at org.neo4j.graphalgo.core.huge.HugeGraph.degree(HugeGraph.java:316)
at org.neo4j.graphalgo.impl.walking.RandomWalk$RandomNextNodeStrategy.getNextNode(RandomWalk.java:163)
at org.neo4j.graphalgo.impl.walking.RandomWalk.doWalk(RandomWalk.java:117)
at org.neo4j.graphalgo.impl.walking.RandomWalk.lambda$compute$0(RandomWalk.java:90)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
at org.neo4j.internal.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:110)

For more detail, see this topic in the community,
https://community.neo4j.com/t/it-takes-forever-in-executing-the-randomwalk-algorithm/44299

**Comment by FlorentinD** [comment]
Hey @AlexOugh,
thank you for reporting this bug.
Your stacktrace is very helpful. Could you share your `gds.graph.create` query and your random walk query (including how you match the source node)?

It is likely that your start node(s) is not projected to the GDS graph. Internally, unmapped nodes return an id of `-1`.
There is a PR in flight to improve the reported error and fail earlier though.

**Comment by AliciaFrame** [comment]
Hey @AlexOugh - can you try out our new RandomWalk implementation on the 1.8 release? We've improved the implementation to be faster, and to provide error messages more promptly. See: https://github.com/neo4j/graph-data-science/releases/tag/1.8.0
