### ISSUE TITLE
gds. cypher dsl in java  meet error  ?

### ISSUE THREAD

**Issue by mullerhai** [neo4j/graph-data-science#151]
HI neo4j :
           I am use  in java project ,meet error ,connect the mac local. neo4j server use java , use the cypher. dsl 
"""

Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.procedure.impl.GlobalProceduresRegistry@559991f5' was successfully initialized, but failed to start. Please see the attached cause exception "com.neo4j.gds.SystemMonitorProc".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:463)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:205)
	... 4 more
Caused by: org.neo4j.internal.kernel.api.exceptions.ProcedureException: Failed to compile procedure defined in `SystemMonitorProc`: com/neo4j/gds/SystemMonitorProc
	at org.neo4j.procedure.impl.ProcedureCompilation.compileProcedure(ProcedureCompilation.java:382)
	at org.neo4j.procedure.impl.ProcedureCompiler.compileProcedure(ProcedureCompiler.java:288)
	at org.neo4j.procedure.impl.ProcedureCompiler.compileProcedure(ProcedureCompiler.java:226)
	at org.neo4j.procedure.impl.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:122)
	at org.neo4j.procedure.impl.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:96)
	at org.neo4j.procedure.impl.GlobalProceduresRegistry.start(GlobalProceduresRegistry.java:383)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442)
	... 6 more
Caused by: java.lang.NoClassDefFoundError: com/neo4j/gds/SystemMonitorProc
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3220)
	at java.base/java.lang.Class.getDeclaredField(Class.java:2567)
	at org.neo4j.procedure.impl.ProcedureCompilation.setAllStaticFields(ProcedureCompilation.java:1168)
	at org.neo4j.procedure.impl.ProcedureCompilation.compileProcedure(ProcedureCompilation.java:375)
	... 12 more
Caused by: java.lang.ClassNotFoundException: com.neo4j.gds.SystemMonitorProc
	at org.neo4j.codegen.CodeLoader.findClass(CodeLoader.java:60)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 17 more
"""
GDS version: 1.8.0
Neo4j version: 4.3.7 and 4.4.2
Operating system:  mac
java. neo4j. jar. version. 4.3.7 and 4.4.2
- [ ] Graph/dataset to reproduce the bug.  Alternatively describe as much as possible the data, e.g., graph size and other schema/structure details.
- [ ] Create Query 
- [ ] Further queries

**Expected behavior**

**Additional context**

**Comment by mullerhai** [comment]
if  I. use this config the program can running 
 properties.put("dbms.security.procedures.unrestricted","gds.*")
    properties.put("dbms.security.procedures.allowlist","gds.pageRank")

but Generally. I. need to load and use all algorithm

    properties.put("dbms.security.procedures.unrestricted","gds.*")
    properties.put("dbms.security.procedures.allowlist","gds.*")

**Comment by s1ck** [comment]
You're right. If you use GDS from within a Java application, you need to manually load all the procedure classes you intend to use.

**Comment by s1ck** [comment]
Here is an issue where @Mats-SX explained the necessary steps: https://github.com/neo4j/graph-data-science/issues/91

**Comment by mullerhai** [comment]
@s1ck  HI friend, could you apply  one  command line  to config the procedure blacklist ,to prevent the  bad [not found ]or  not necessary proc  load?

**Comment by Mats-SX** [comment]
@mullerhai Since you're working in Java, you must do this with code. If you do it manually, it will get [pretty verbose, such as in this test](https://github.com/neo4j/graph-data-science/blob/439816caa21cc0467d63bd4f3a5977a3e23a752c/proc/src/test/java/org/neo4j/graphalgo/ListProcTest.java#L268-L336).

Because of this inconvenience, I would repeat my recommendation from [this answer](https://github.com/neo4j/graph-data-science/issues/91#issuecomment-727895099) and use a reflection-based registration instead. However, since authoring that post we have made a couple of improvements. The class [TestProcedureAndFunctionScanner](https://github.com/neo-technology/graph-analytics/blob/818d6c1232b81707f39c9396eab477c17c095f76/public/proc/test/src/main/java/org/neo4j/gds/utils/TestProcedureAndFunctionScanner.java) makes it convenient to acquire the classes necessary to register. Please feel free to copy the code to fit your purposes!

Regards
Mats

**Comment by s1ck** [comment]
I'm closing this since it's a configuration problem which has already been addressed in #91
