### ISSUE TITLE
building on Ubuntu 19.10

### ISSUE THREAD

**Issue by rotten** [neo4j/graph-data-science#28]
I attempted to build this on Ubuntu 19.10 and ran into some issues.  I was hoping if I could get it to build it would work with Neo4j 4.0.3 since I don't want to revert my database now that I've got it set up and loaded with data, and I'd really like to use some of the algos().

Firstly, I had to install groovy.
Then, because Ubuntu 19.10 uses OpenJDK-14, I had to bump the gradle version in `gradle/wrapper/gradle-wrapper.properties` to 6.3.

At that point, `./gradlew build` worked except 7 of the 193 of the tests failed.

```
ClosenessCentralityDiscoTest. testHuge()
YensTest. test()
NormalizedCentralityResultTest. doubleArrayResultExport()
NormalizedCentralityResultTest. l1Norm()
NormalizedCentralityResultTest. l2Norm()
NormalizedCentralityResultTest. maxNormalization()
NormalizedCentralityResultTest. noNormalization()
```

All of them fail with the same error.

For example:
```doubleArrayResultExport()
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class org.neo4j.graphalgo.core.write.NodePropertyExporter.
Can not mock final classes with the following settings :
 - explicit serialization (e.g. withSettings().serializable())
 - extra interfaces (e.g. withSettings().extraInterfaces(...))

You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class org.neo4j.graphalgo.utils.StatementApi, class java.lang.Object, class org.neo4j.graphalgo.core.write.NodePropertyExporter]
	at org.neo4j.graphalgo.results.NormalizedCentralityResultTest.doubleArrayResultExport(NormalizedCentralityResultTest.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class org.neo4j.graphalgo.utils.StatementApi, class java.lang.Object, class org.neo4j.graphalgo.core.write.NodePropertyExporter]
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
	... 89 more
Caused by: java.lang.IllegalStateException: 
Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:176)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:152)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMockType(InlineByteBuddyMockMaker.java:197)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:178)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
	at org.mockito.Mockito.mock(Mockito.java:1908)
	at org.mockito.Mockito.mock(Mockito.java:1817)
	... 89 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 58
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:184)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:166)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:152)
	at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:82)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3390)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1930)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:217)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:120)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3396)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:253)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:173)
	... 103 more```

So I'm thinking there is probably something else, and probably relatively simple, that I'm missing which will resolve all of these tests at the same time.  Unfortunately it has been many years since I coded in Java with any regularity or intent, so I'm not sure where to go from here.

**Comment by vnickolov** [comment]
Hi @rotten, 

Thank you for reaching out.

The current version of the library is being developed using Java 11 (the same as Neo4j 4.0.x).

I hope this helps.

**Comment by rotten** [comment]
Ok.  I had to completely purge openjdk 14, and openjdk 8 (which I'd installed to try to get Gephi working again) and revert Gradle to the older version before it would build.  Thank you for your help.  I'll give it a try now.  Why is such new cool stuff running on such old versions of java?

**Comment by vnickolov** [comment]
Hi @rotten,

Please let us know if you managed to get the library built. 
Java 11 is the latest LTS support version which is the reason for it to be used (14 was released earlier this year).

**Comment by knutwalker** [comment]
@rotten We updated the master branch to use gradle 6.3 yesterday. Tests don't seem to run on java 14, but you can execute `./gradlew shadowCopy -x test` and then get your jar from `build/distributions`. (I just did so using 14.0.0 from Adopt OpenJDK)

**Comment by rotten** [comment]
Thank you.  Yes, I can build it now with openjdk-11.  I didn't realize that openjdk did the LTS/interim release strategy too, so that makes sense.

Thanks for Gradle 6.3!   I just did a pull, and that built ok as well.  I'll stick with openjdk-11 for this week's project, and circle back to openjdk-14 in a week or two once I get past my current deadline.

**Comment by Mats-SX** [comment]
@rotten Just as an aside, if you just want to _use_ the library rather than write your own code in it, it may be more convenient to just install one of our released artifacts instead. Now, you won't find a 4.0 compatible version released just yet, but that is next on our list.

**Comment by rotten** [comment]
I needed the 4.0 compatibility.  It is working great for what I needed it for.  Thanks for the tip.

**Comment by vnickolov** [comment]
@rotten you should be able to build the project with JDK14 with the latest changes.

**Comment by xxks-kkk** [comment]
> Hi @rotten,
> 
> Thank you for reaching out.
> 
> The current version of the library is being developed using Java 11 (the same as Neo4j 4.0.x).
> 
> I hope this helps.

Which specific Java 11 do we use to build this repo?

I use 

```
$ java --version
java 11.0.7 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
```

with commit ID: bb668851f006a2c4a4e2125ce6d28d304915376d

And then I run ` ./gradlew build`:

```
$ ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/zeyuanhu/Documents/graph-data-science/doc/build.gradle' line: 36

* What went wrong:
A problem occurred evaluating project ':doc'.
> Project with path ':alpha-embeddings' could not be found in project ':doc'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 925ms
```

I ad-hoc fix the above issue

```
$ cat a.patch
diff --git a/doc/build.gradle b/doc/build.gradle
index c474acb7b..a9907f557 100644
--- a/doc/build.gradle
+++ b/doc/build.gradle
@@ -33,7 +33,7 @@ dependencies {
     implementation     group: 'org.asciidoctor', name: 'asciidoctorj', version: ver.doc.'asciidoctorj'

     testImplementation project(':proc')
-    testImplementation project(':alpha-embeddings')
+//    testImplementation project(':alpha-embeddings')

     testImplementation group: 'org.reflections',  name: 'reflections',       version: ver.doc.'reflections'
 }
```
and then run the gradle command again. Now, I hit the exception:

```
$ ./gradlew build
> Task :cypher-printer-4.1:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cypher-printer-4.1:compileJava'.
> Could not resolve all files for configuration ':cypher-printer-4.1:compileClasspath'.
   > Could not find org.neo4j:annotations:4.1.0-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/neo4j/annotations/4.1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/neo4j/annotations/4.1.0-SNAPSHOT/annotations-4.1.0-SNAPSHOT.pom
       - file:/Users/zeyuanhu/Documents/graph-data-science/neo4j-repo/org/neo4j/annotations/4.1.0-SNAPSHOT/maven-metadata.xml
       - file:/Users/zeyuanhu/Documents/graph-data-science/neo4j-repo/org/neo4j/annotations/4.1.0-SNAPSHOT/annotations-4.1.0-SNAPSHOT.pom
       - file:/Users/zeyuanhu/.m2/repository/org/neo4j/annotations/4.1.0-SNAPSHOT/maven-metadata.xml
       - file:/Users/zeyuanhu/.m2/repository/org/neo4j/annotations/4.1.0-SNAPSHOT/annotations-4.1.0-SNAPSHOT.pom
     Required by:
         project :cypher-printer-4.1
   > Could not find org.neo4j:neo4j-ast:4.1.0-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/neo4j/neo4j-ast/4.1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/neo4j/neo4j-ast/4.1.0-SNAPSHOT/neo4j-ast-4.1.0-SNAPSHOT.pom
       - file:/Users/zeyuanhu/Documents/graph-data-science/neo4j-repo/org/neo4j/neo4j-ast/4.1.0-SNAPSHOT/maven-metadata.xml
       - file:/Users/zeyuanhu/Documents/graph-data-science/neo4j-repo/org/neo4j/neo4j-ast/4.1.0-SNAPSHOT/neo4j-ast-4.1.0-SNAPSHOT.pom
       - file:/Users/zeyuanhu/.m2/repository/org/neo4j/neo4j-ast/4.1.0-SNAPSHOT/maven-metadata.xml
       - file:/Users/zeyuanhu/.m2/repository/org/neo4j/neo4j-ast/4.1.0-SNAPSHOT/neo4j-ast-4.1.0-SNAPSHOT.pom
     Required by:
         project :cypher-printer-4.1
   > Could not find org.neo4j:neo4j-expressions:4.1.0-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/neo4j/neo4j-expressions/4.1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/neo4j/neo4j-expressions/4.1.0-SNAPSHOT/neo4j-expressions-4.1.0-SNAPSHOT.pom
       - file:/Users/zeyuanhu/Documents/graph-data-science/neo4j-repo/org/neo4j/neo4j-expressions/4.1.0-SNAPSHOT/maven-metadata.xml
       - file:/Users/zeyuanhu/Documents/graph-data-science/neo4j-repo/org/neo4j/neo4j-expressions/4.1.0-SNAPSHOT/neo4j-expressions-4.1.0-SNAPSHOT.pom
       - file:/Users/zeyuanhu/.m2/repository/org/neo4j/neo4j-expressions/4.1.0-SNAPSHOT/maven-metadata.xml
       - file:/Users/zeyuanhu/.m2/repository/org/neo4j/neo4j-expressions/4.1.0-SNAPSHOT/neo4j-expressions-4.1.0-SNAPSHOT.pom
     Required by:
         project :cypher-printer-4.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
9 actionable tasks: 1 executed, 8 up-to-date
```

What I need to do here? Thanks!

**Comment by jjaderberg** [comment]
@xxks-kkk Your Java version is fine. There are two problems. The first problem is that we introduced a buggy dependency. You already figured out a workaround for that (and it has also been fixed on master). The second is that we switched to target compatibility with both Neo4j versions 4.0.x and 4.1.x. This introduces a Neo4j 4.1.x dependency. We did this to prepare for the upcoming Neo4j 4.1.0 release. Unfortunately, this means that, since Neo4j 4.1.0 isn't released yet, you need to provide that dependency yourself. We added instructions to the [readme](https://github.com/neo4j/graph-data-science/#building-the-library) for how to do that.
Neo4j 4.1.0 will be released soon. This additional step wont be necessary then.
Please open a new issue if you have further trouble.
