### ISSUE TITLE
GDS compatibility with Neo4j 5.23.0

### ISSUE THREAD

**Issue by ciropom** [neo4j/graph-data-science#326]
**Describe the bug**
Tried to use gds 2.8.0 plugin in neo4j 5.23.0, but the server failed to start

**To Reproduce**
installing gds plugin in neo4j 5.20

GDS version: 2.8.0
Neo4j version: 5.23.0
Operating system: Ubuntu 20.04.6 LTS

**Additional context**
```
2024-08-26 07:42:41.291+0000 INFO  ======== Neo4j 5.23.0 ========
2024-08-26 07:42:41.686+0000 ERROR Failed to start Neo4j on localhost:7474.
java.lang.RuntimeException: Error starting Neo4j database server at /var/lib/neo4j/data/databases
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:280) ~[neo4j-5.23.0.jar:5.23.0]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:215) ~[neo4j-5.23.0.jar:5.23.0]
	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:38) ~[neo4j-5.23.0.jar:5.23.0]
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:184) [neo4j-5.23.0.jar:5.23.0]
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:99) [neo4j-5.23.0.jar:5.23.0]
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:30) [neo4j-5.23.0.jar:5.23.0]
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.GlobalExtensions@7923f5b3' failed to initialize. Please see the attached cause exception "org.neo4j.internal.batchimport.Configuration".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:334) ~[neo4j-common-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.23.0.jar:5.23.0]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:271) ~[neo4j-5.23.0.jar:5.23.0]
	... 5 more
Caused by: org.neo4j.kernel.extension.FailedToBuildExtensionException: Failed to build kernel extension Extension:GraphDataScienceExtension[gds.closed] because it is compiled with a reference to a class, method, or field, that is not in the class path: 'org/neo4j/internal/batchimport/Configuration'. The most common cause of this problem, is that Neo4j has been upgraded without also upgrading all installed extensions, such as APOC. Make sure that all of your extensions are build against your specific version of Neo4j.
	at org.neo4j.kernel.extension.ExtensionFailureStrategies.wrap(ExtensionFailureStrategies.java:56) ~[neo4j-kernel-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.extension.ExtensionFailureStrategies$1.handle(ExtensionFailureStrategies.java:68) ~[neo4j-kernel-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:68) ~[neo4j-kernel-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.23.0.jar:5.23.0]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:271) ~[neo4j-5.23.0.jar:5.23.0]
	... 5 more
Caused by: java.lang.NoClassDefFoundError: org/neo4j/internal/batchimport/Configuration
	at org.neo4j.gds.procedures.integration.LogAccessor.getLog(LogAccessor.java:33) ~[neo4j-graph-data-science-2.8.0.jar:?]
	at com.neo4j.gds.extension.GraphDataScienceExtension.newInstance(GraphDataScienceExtension.java:67) ~[neo4j-graph-data-science-2.8.0.jar:?]
	at com.neo4j.gds.extension.GraphDataScienceExtension.newInstance(GraphDataScienceExtension.java:53) ~[neo4j-graph-data-science-2.8.0.jar:?]
	at org.neo4j.kernel.extension.AbstractExtensions.newInstance(AbstractExtensions.java:124) ~[neo4j-kernel-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:62) ~[neo4j-kernel-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.23.0.jar:5.23.0]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:271) ~[neo4j-5.23.0.jar:5.23.0]
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.internal.batchimport.Configuration
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at org.neo4j.gds.procedures.integration.LogAccessor.getLog(LogAccessor.java:33) ~[neo4j-graph-data-science-2.8.0.jar:?]
	at com.neo4j.gds.extension.GraphDataScienceExtension.newInstance(GraphDataScienceExtension.java:67) ~[neo4j-graph-data-science-2.8.0.jar:?]
	at com.neo4j.gds.extension.GraphDataScienceExtension.newInstance(GraphDataScienceExtension.java:53) ~[neo4j-graph-data-science-2.8.0.jar:?]
	at org.neo4j.kernel.extension.AbstractExtensions.newInstance(AbstractExtensions.java:124) ~[neo4j-kernel-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:62) ~[neo4j-kernel-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.23.0.jar:5.23.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.23.0.jar:5.23.0]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:271) ~[neo4j-5.23.0.jar:5.23.0]
	... 5 more
2024-08-26 07:42:41.707+0000 INFO  Neo4j Server shutdown initiated by request
2024-08-26 07:42:41.708+0000 INFO  Stopped.
```

similar to #310

**Comment by ciropom** [comment]
thank you, I was using CE version, and on the website I was able to find only version 2.8.0.

**Comment by ciropom** [comment]
I confirm that version 2.9.0 works. Thank you.
