### ISSUE TITLE
kmin spanning tree ends with ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1024

### ISSUE THREAD

**Issue by amitabak-MA** [neo4j/graph-data-science#40]
2020-05-17 04:47:24.029+0000 INFO  [neo4j.BoltWorker-37 [bolt] [/127.0.0.1:50983] ] LOADING 
2020-05-17 04:47:24.571+0000 WARN  Computation failed Index -1 out of bounds for length 1024
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1024
        at org.neo4j.graphalgo.core.huge.AdjacencyOffsets$SinglePageOffsets.get(AdjacencyOffsets.java:126)
        at org.neo4j.graphalgo.core.huge.HugeGraph.adjacencyCursorForIteration(HugeGraph.java:340)
        at org.neo4j.graphalgo.core.huge.HugeGraph.runForEach(HugeGraph.java:330)
        at org.neo4j.graphalgo.core.huge.HugeGraph.forEachRelationship(HugeGraph.java:249)
        at org.neo4j.graphalgo.impl.spanningTrees.Prim.compute(Prim.java:88)
        at org.neo4j.graphalgo.impl.spanningTrees.KSpanningTree.compute(KSpanningTree.java:81)
        at org.neo4j.graphalgo.impl.spanningTrees.KSpanningTree.compute(KSpanningTree.java:41)
        at org.neo4j.graphalgo.AlgoBaseProc.lambda$compute$3(AlgoBaseProc.java:394)
        at org.neo4j.graphalgo.BaseProc.runWithExceptionLogging(BaseProc.java:92)
        at org.neo4j.graphalgo.AlgoBaseProc.compute(AlgoBaseProc.java:390)
        at org.neo4j.graphalgo.AlgoBaseProc.compute(AlgoBaseProc.java:350)
        at org.neo4j.graphalgo.spanningtree.KSpanningTreeProc.computeAndWrite(KSpanningTreeProc.java:83)
        at org.neo4j.graphalgo.spanningtree.KSpanningTreeProc.kmin(KSpanningTreeProc.java:79)
        at org.neo4j.kernel.impl.proc.GeneratedProcedure_write851277073944438.apply(Unknown Source)
        at org.neo4j.procedure.impl.ProcedureRegistry.callProcedure(ProcedureRegistry.java:208)
        at org.neo4j.procedure.impl.GlobalProceduresRegistry.callProcedure(GlobalProceduresRegistry.java:323)
        at org.neo4j.kernel.impl.newapi.AllStoreHolder.callProcedure(AllStoreHolder.java:926)

**Comment by amitabak-MA** [comment]
Adding protective code in AdjacencyOffsets. solves the issue

  @Override
        long get(long index) {
            if((index <0) || (page.length <= index)) {
                return 0L;
            }
            return page[(int) index];
        }

**Comment by FlorentinD** [comment]
looking at the call stack, it looks like the `startNodeId` does not exists in the loaded graph.
Its still a bug, but adding the guard in the `get` has a high cost. Better to check earlier, so that -1 will never reach this code-path
